service: sakura-twitter-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  environment:
    CONSUMER_KEY: ${file(./env/env.yml):CONSUMER_KEY}
    CONSUMER_SECRET: ${file(./env/env.yml):CONSUMER_SECRET}

functions:
  request_token:
    handler: src/request_token.main
    events:
      - http:
          path: request_token
          method: get
  access_token:
    handler: src/access_token.main
    events:
      - http:
          path: access_token
          method: get
  icon:
    handler: src/icon.main
    events:
      - http:
          path: icon
          method: get
  tweet:
    handler: src/tweet.main
    events:
      - http:
          path: tweet
          method: post
