service: sakura-twitter-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  environment:
    API_KEY: ${file(./env/env.yml):API_KEY}
    API_SECRET: ${file(./env/env.yml):API_SECRET}

plugins:
  - serverless-python-requirements

functions:
  request_token:
    handler: src/request_token.get
    events:
      - http:
          path: request_token
          method: get
  access_token:
    handler: src/access_token.post
    events:
      - http:
          path: access_token
          method: post
  profile_image_url:
    handler: src/profile_image_url.post
    events:
      - http:
          path: profile_image_url
          method: post
  tweet:
    handler: src/tweet.post
    events:
      - http:
          path: tweet
          method: post
